### ISSUE TITLE
Running yarn build resulted error

### ISSUE THREAD

**Issue by s-en-o** [GOVTNZ/govtnz-design-system#102]
I tried to clone the project following the [guideline for contributing](https://github.com/GOVTNZ/govtnz-design-system/blob/master/CONTRIBUTING.md) but run into error.
The message below showed after running `yarn build` (`yarn build:all` has been removed).

```
C:\Users\Seno\Sites\govtnz-design-system\packages\govtnz-ds\src\index.ts:1
import fs from 'fs';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at Object.<anonymous> (C:\Users\Seno\Sites\govtnz-design-system\node_modules\@babel\node\lib\_babel-node.js:180:21)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

Please advise, Cheers!

**Comment by holloway** [comment]
Hi, I'm not able to reproduce this issue. Did you run `nvm` before installing via `yarn` ?

**Comment by s-en-o** [comment]
Hey @holloway, I don't think I did as my npm version is `12.13.0`. Do you think that might cause the issue?

**Comment by holloway** [comment]
I think NPM is only up to version 7.x, but Node should be 12.13.0 so that should be fine.

Try deleting your `node_modules` and then

```
nvm use
yarn
yarn build
```

**Comment by s-en-o** [comment]
Thanks @holloway, apparently it works on Mac but not on Windows system. Closing, cheers.
